type Food {
  _id: ID
  name: String!
  price: Int!
  shift: Boolean!
  extra: [String]
  side: [String]
}

type Drink {
  _id: ID
  name: String!
  price: Int!
}

type Order {
  _id: ID
  food: [Food]!
  drink: [Drink]!
  total: Int!
  client: String!
  employee: User!
}
type User {
  _id: ID
  username: String! @unique
  password: String!
}
